package epss.repository.dao;

import epss.repository.model.EsInitCust;
import epss.repository.model.EsInitCustExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EsInitCustMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.ES_INIT_CUST
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    int countByExample(EsInitCustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.ES_INIT_CUST
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    int deleteByExample(EsInitCustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.ES_INIT_CUST
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.ES_INIT_CUST
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    int insert(EsInitCust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.ES_INIT_CUST
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    int insertSelective(EsInitCust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.ES_INIT_CUST
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    List<EsInitCust> selectByExample(EsInitCustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.ES_INIT_CUST
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    EsInitCust selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.ES_INIT_CUST
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    int updateByExampleSelective(@Param("record") EsInitCust record, @Param("example") EsInitCustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.ES_INIT_CUST
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    int updateByExample(@Param("record") EsInitCust record, @Param("example") EsInitCustExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.ES_INIT_CUST
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    int updateByPrimaryKeySelective(EsInitCust record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.ES_INIT_CUST
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    int updateByPrimaryKey(EsInitCust record);
}