package skyline.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import skyline.repository.model.Ptmenu;
import skyline.repository.model.PtmenuExample;

public interface PtmenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Thu Aug 21 20:41:09 CST 2014
     */
    int countByExample(PtmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Thu Aug 21 20:41:09 CST 2014
     */
    int deleteByExample(PtmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Thu Aug 21 20:41:09 CST 2014
     */
    int insert(Ptmenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Thu Aug 21 20:41:09 CST 2014
     */
    int insertSelective(Ptmenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Thu Aug 21 20:41:09 CST 2014
     */
    List<Ptmenu> selectByExample(PtmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Thu Aug 21 20:41:09 CST 2014
     */
    int updateByExampleSelective(@Param("record") Ptmenu record, @Param("example") PtmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Thu Aug 21 20:41:09 CST 2014
     */
    int updateByExample(@Param("record") Ptmenu record, @Param("example") PtmenuExample example);
}