package epss.repository.dao;

import epss.repository.model.ProgMatqtyItem;
import epss.repository.model.ProgMatqtyItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProgMatqtyItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.PROG_MATQTY_ITEM
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    int countByExample(ProgMatqtyItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.PROG_MATQTY_ITEM
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    int deleteByExample(ProgMatqtyItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.PROG_MATQTY_ITEM
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.PROG_MATQTY_ITEM
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    int insert(ProgMatqtyItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.PROG_MATQTY_ITEM
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    int insertSelective(ProgMatqtyItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.PROG_MATQTY_ITEM
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    List<ProgMatqtyItem> selectByExample(ProgMatqtyItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.PROG_MATQTY_ITEM
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    ProgMatqtyItem selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.PROG_MATQTY_ITEM
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    int updateByExampleSelective(@Param("record") ProgMatqtyItem record, @Param("example") ProgMatqtyItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.PROG_MATQTY_ITEM
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    int updateByExample(@Param("record") ProgMatqtyItem record, @Param("example") ProgMatqtyItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.PROG_MATQTY_ITEM
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    int updateByPrimaryKeySelective(ProgMatqtyItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.PROG_MATQTY_ITEM
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    int updateByPrimaryKey(ProgMatqtyItem record);
}