package epss.repository.model;

public class EsInitPowerHisKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.FLOW_CTRL_HIS.INFO_TYPE
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    private String powerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.FLOW_CTRL_HIS.INFO_PKID
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    private String powerPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.FLOW_CTRL_HIS.STAGE_NO
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    private String stageNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.FLOW_CTRL_HIS.INFO_TYPE
     *
     * @return the value of EPSS.FLOW_CTRL_HIS.INFO_TYPE
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    public String getPowerType() {
        return powerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.FLOW_CTRL_HIS.INFO_TYPE
     *
     * @param powerType the value for EPSS.FLOW_CTRL_HIS.INFO_TYPE
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    public void setPowerType(String powerType) {
        this.powerType = powerType == null ? null : powerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.FLOW_CTRL_HIS.INFO_PKID
     *
     * @return the value of EPSS.FLOW_CTRL_HIS.INFO_PKID
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    public String getPowerPkid() {
        return powerPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.FLOW_CTRL_HIS.INFO_PKID
     *
     * @param powerPkid the value for EPSS.FLOW_CTRL_HIS.INFO_PKID
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    public void setPowerPkid(String powerPkid) {
        this.powerPkid = powerPkid == null ? null : powerPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.FLOW_CTRL_HIS.STAGE_NO
     *
     * @return the value of EPSS.FLOW_CTRL_HIS.STAGE_NO
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    public String getStageNo() {
        return stageNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.FLOW_CTRL_HIS.STAGE_NO
     *
     * @param stageNo the value for EPSS.FLOW_CTRL_HIS.STAGE_NO
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    public void setStageNo(String stageNo) {
        this.stageNo = stageNo == null ? null : stageNo.trim();
    }
}