package epss.repository.model;

public class SignPart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.SIGN_PART.PKID
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.SIGN_PART.ID
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.SIGN_PART.NAME
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.SIGN_PART.MOBILEPHONE
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    private String mobilephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.SIGN_PART.EMAIL
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.SIGN_PART.OPERPHONE
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    private String operphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.SIGN_PART.OTHERPHONE
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    private String otherphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.SIGN_PART.FAX
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.SIGN_PART.ARCHIVED_FLAG
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    private String archivedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.SIGN_PART.ORIGIN_FLAG
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    private String originFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.SIGN_PART.CREATED_BY
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.SIGN_PART.CREATED_TIME
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    private String createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.SIGN_PART.UPDATED_BY
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.SIGN_PART.UPDATED_TIME
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    private String updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.SIGN_PART.REC_VERSION
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    private Integer recVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.SIGN_PART.REMARK
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.SIGN_PART.PKID
     *
     * @return the value of EPSS.SIGN_PART.PKID
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.SIGN_PART.PKID
     *
     * @param pkid the value for EPSS.SIGN_PART.PKID
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.SIGN_PART.ID
     *
     * @return the value of EPSS.SIGN_PART.ID
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.SIGN_PART.ID
     *
     * @param id the value for EPSS.SIGN_PART.ID
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.SIGN_PART.NAME
     *
     * @return the value of EPSS.SIGN_PART.NAME
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.SIGN_PART.NAME
     *
     * @param name the value for EPSS.SIGN_PART.NAME
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.SIGN_PART.MOBILEPHONE
     *
     * @return the value of EPSS.SIGN_PART.MOBILEPHONE
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.SIGN_PART.MOBILEPHONE
     *
     * @param mobilephone the value for EPSS.SIGN_PART.MOBILEPHONE
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone == null ? null : mobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.SIGN_PART.EMAIL
     *
     * @return the value of EPSS.SIGN_PART.EMAIL
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.SIGN_PART.EMAIL
     *
     * @param email the value for EPSS.SIGN_PART.EMAIL
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.SIGN_PART.OPERPHONE
     *
     * @return the value of EPSS.SIGN_PART.OPERPHONE
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public String getOperphone() {
        return operphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.SIGN_PART.OPERPHONE
     *
     * @param operphone the value for EPSS.SIGN_PART.OPERPHONE
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public void setOperphone(String operphone) {
        this.operphone = operphone == null ? null : operphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.SIGN_PART.OTHERPHONE
     *
     * @return the value of EPSS.SIGN_PART.OTHERPHONE
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public String getOtherphone() {
        return otherphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.SIGN_PART.OTHERPHONE
     *
     * @param otherphone the value for EPSS.SIGN_PART.OTHERPHONE
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public void setOtherphone(String otherphone) {
        this.otherphone = otherphone == null ? null : otherphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.SIGN_PART.FAX
     *
     * @return the value of EPSS.SIGN_PART.FAX
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.SIGN_PART.FAX
     *
     * @param fax the value for EPSS.SIGN_PART.FAX
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.SIGN_PART.ARCHIVED_FLAG
     *
     * @return the value of EPSS.SIGN_PART.ARCHIVED_FLAG
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public String getArchivedFlag() {
        return archivedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.SIGN_PART.ARCHIVED_FLAG
     *
     * @param archivedFlag the value for EPSS.SIGN_PART.ARCHIVED_FLAG
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public void setArchivedFlag(String archivedFlag) {
        this.archivedFlag = archivedFlag == null ? null : archivedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.SIGN_PART.ORIGIN_FLAG
     *
     * @return the value of EPSS.SIGN_PART.ORIGIN_FLAG
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public String getOriginFlag() {
        return originFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.SIGN_PART.ORIGIN_FLAG
     *
     * @param originFlag the value for EPSS.SIGN_PART.ORIGIN_FLAG
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public void setOriginFlag(String originFlag) {
        this.originFlag = originFlag == null ? null : originFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.SIGN_PART.CREATED_BY
     *
     * @return the value of EPSS.SIGN_PART.CREATED_BY
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.SIGN_PART.CREATED_BY
     *
     * @param createdBy the value for EPSS.SIGN_PART.CREATED_BY
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.SIGN_PART.CREATED_TIME
     *
     * @return the value of EPSS.SIGN_PART.CREATED_TIME
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.SIGN_PART.CREATED_TIME
     *
     * @param createdTime the value for EPSS.SIGN_PART.CREATED_TIME
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime == null ? null : createdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.SIGN_PART.UPDATED_BY
     *
     * @return the value of EPSS.SIGN_PART.UPDATED_BY
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.SIGN_PART.UPDATED_BY
     *
     * @param updatedBy the value for EPSS.SIGN_PART.UPDATED_BY
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.SIGN_PART.UPDATED_TIME
     *
     * @return the value of EPSS.SIGN_PART.UPDATED_TIME
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public String getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.SIGN_PART.UPDATED_TIME
     *
     * @param updatedTime the value for EPSS.SIGN_PART.UPDATED_TIME
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public void setUpdatedTime(String updatedTime) {
        this.updatedTime = updatedTime == null ? null : updatedTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.SIGN_PART.REC_VERSION
     *
     * @return the value of EPSS.SIGN_PART.REC_VERSION
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public Integer getRecVersion() {
        return recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.SIGN_PART.REC_VERSION
     *
     * @param recVersion the value for EPSS.SIGN_PART.REC_VERSION
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public void setRecVersion(Integer recVersion) {
        this.recVersion = recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.SIGN_PART.REMARK
     *
     * @return the value of EPSS.SIGN_PART.REMARK
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.SIGN_PART.REMARK
     *
     * @param remark the value for EPSS.SIGN_PART.REMARK
     *
     * @mbggenerated Sun Jun 08 03:16:01 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}