package epss.repository.model;

import java.math.BigDecimal;

public class EsItemStlSubcttEngP {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.PKID
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.SUBSTL_TYPE
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private String substlType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ID
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.SUBCTT_PKID
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private String subcttPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.SUBCTT_NAME
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private String subcttName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.PERIOD_NO
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private String periodNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.SUBCTT_ITEM_PKID
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private String subcttItemPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.SUBCTT_ITEM_NAME
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private String subcttItemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.UNIT
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.UNIT_PRICE
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private BigDecimal unitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.THIS_STAGE_QTY
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private BigDecimal thisStageQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.THIS_STAGE_AMT
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private BigDecimal thisStageAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ADD_UP_QTY
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private BigDecimal addUpQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ADD_UP_AMT
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private BigDecimal addUpAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ARCHIVED_FLAG
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private String archivedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ORIGIN_FLAG
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private String originFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.CREATED_BY
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.CREATED_BY_NAME
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private String createdByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.CREATED_DATE
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private String createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.LAST_UPD_BY
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private String lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.LAST_UPD_BY_NAME
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private String lastUpdByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.LAST_UPD_DATE
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private String lastUpdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.REC_VERSION
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private Integer recVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.REMARK
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.CONTRACT_QUANTITY
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private BigDecimal contractQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.CONTRACT_AMOUNT
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private BigDecimal contractAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.STRNO
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private String strno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ROW_NO
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    private Integer rowNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.PKID
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.PKID
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.PKID
     *
     * @param pkid the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.PKID
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.SUBSTL_TYPE
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.SUBSTL_TYPE
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public String getSubstlType() {
        return substlType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.SUBSTL_TYPE
     *
     * @param substlType the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.SUBSTL_TYPE
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setSubstlType(String substlType) {
        this.substlType = substlType == null ? null : substlType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ID
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ID
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ID
     *
     * @param id the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ID
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.SUBCTT_PKID
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.SUBCTT_PKID
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public String getSubcttPkid() {
        return subcttPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.SUBCTT_PKID
     *
     * @param subcttPkid the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.SUBCTT_PKID
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setSubcttPkid(String subcttPkid) {
        this.subcttPkid = subcttPkid == null ? null : subcttPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.SUBCTT_NAME
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.SUBCTT_NAME
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public String getSubcttName() {
        return subcttName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.SUBCTT_NAME
     *
     * @param subcttName the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.SUBCTT_NAME
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setSubcttName(String subcttName) {
        this.subcttName = subcttName == null ? null : subcttName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.PERIOD_NO
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.PERIOD_NO
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public String getPeriodNo() {
        return periodNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.PERIOD_NO
     *
     * @param periodNo the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.PERIOD_NO
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setPeriodNo(String periodNo) {
        this.periodNo = periodNo == null ? null : periodNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.SUBCTT_ITEM_PKID
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.SUBCTT_ITEM_PKID
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public String getSubcttItemPkid() {
        return subcttItemPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.SUBCTT_ITEM_PKID
     *
     * @param subcttItemPkid the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.SUBCTT_ITEM_PKID
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setSubcttItemPkid(String subcttItemPkid) {
        this.subcttItemPkid = subcttItemPkid == null ? null : subcttItemPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.SUBCTT_ITEM_NAME
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.SUBCTT_ITEM_NAME
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public String getSubcttItemName() {
        return subcttItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.SUBCTT_ITEM_NAME
     *
     * @param subcttItemName the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.SUBCTT_ITEM_NAME
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setSubcttItemName(String subcttItemName) {
        this.subcttItemName = subcttItemName == null ? null : subcttItemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.UNIT
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.UNIT
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.UNIT
     *
     * @param unit the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.UNIT
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.UNIT_PRICE
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.UNIT_PRICE
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.UNIT_PRICE
     *
     * @param unitPrice the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.UNIT_PRICE
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.THIS_STAGE_QTY
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.THIS_STAGE_QTY
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public BigDecimal getThisStageQty() {
        return thisStageQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.THIS_STAGE_QTY
     *
     * @param thisStageQty the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.THIS_STAGE_QTY
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setThisStageQty(BigDecimal thisStageQty) {
        this.thisStageQty = thisStageQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.THIS_STAGE_AMT
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.THIS_STAGE_AMT
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public BigDecimal getThisStageAmt() {
        return thisStageAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.THIS_STAGE_AMT
     *
     * @param thisStageAmt the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.THIS_STAGE_AMT
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setThisStageAmt(BigDecimal thisStageAmt) {
        this.thisStageAmt = thisStageAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ADD_UP_QTY
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ADD_UP_QTY
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public BigDecimal getAddUpQty() {
        return addUpQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ADD_UP_QTY
     *
     * @param addUpQty the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ADD_UP_QTY
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setAddUpQty(BigDecimal addUpQty) {
        this.addUpQty = addUpQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ADD_UP_AMT
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ADD_UP_AMT
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public BigDecimal getAddUpAmt() {
        return addUpAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ADD_UP_AMT
     *
     * @param addUpAmt the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ADD_UP_AMT
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setAddUpAmt(BigDecimal addUpAmt) {
        this.addUpAmt = addUpAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ARCHIVED_FLAG
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ARCHIVED_FLAG
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public String getArchivedFlag() {
        return archivedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ARCHIVED_FLAG
     *
     * @param archivedFlag the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ARCHIVED_FLAG
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setArchivedFlag(String archivedFlag) {
        this.archivedFlag = archivedFlag == null ? null : archivedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ORIGIN_FLAG
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ORIGIN_FLAG
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public String getOriginFlag() {
        return originFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ORIGIN_FLAG
     *
     * @param originFlag the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ORIGIN_FLAG
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setOriginFlag(String originFlag) {
        this.originFlag = originFlag == null ? null : originFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.CREATED_BY
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.CREATED_BY
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.CREATED_BY
     *
     * @param createdBy the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.CREATED_BY
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.CREATED_BY_NAME
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.CREATED_BY_NAME
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public String getCreatedByName() {
        return createdByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.CREATED_BY_NAME
     *
     * @param createdByName the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.CREATED_BY_NAME
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setCreatedByName(String createdByName) {
        this.createdByName = createdByName == null ? null : createdByName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.CREATED_DATE
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.CREATED_DATE
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public String getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.CREATED_DATE
     *
     * @param createdDate the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.CREATED_DATE
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate == null ? null : createdDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.LAST_UPD_BY
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.LAST_UPD_BY
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.LAST_UPD_BY
     *
     * @param lastUpdBy the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.LAST_UPD_BY
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.LAST_UPD_BY_NAME
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.LAST_UPD_BY_NAME
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public String getLastUpdByName() {
        return lastUpdByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.LAST_UPD_BY_NAME
     *
     * @param lastUpdByName the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.LAST_UPD_BY_NAME
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setLastUpdByName(String lastUpdByName) {
        this.lastUpdByName = lastUpdByName == null ? null : lastUpdByName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.LAST_UPD_DATE
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.LAST_UPD_DATE
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public String getLastUpdDate() {
        return lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.LAST_UPD_DATE
     *
     * @param lastUpdDate the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.LAST_UPD_DATE
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setLastUpdDate(String lastUpdDate) {
        this.lastUpdDate = lastUpdDate == null ? null : lastUpdDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.REC_VERSION
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.REC_VERSION
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public Integer getRecVersion() {
        return recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.REC_VERSION
     *
     * @param recVersion the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.REC_VERSION
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setRecVersion(Integer recVersion) {
        this.recVersion = recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.REMARK
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.REMARK
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.REMARK
     *
     * @param remark the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.REMARK
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.CONTRACT_QUANTITY
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.CONTRACT_QUANTITY
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public BigDecimal getContractQuantity() {
        return contractQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.CONTRACT_QUANTITY
     *
     * @param contractQuantity the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.CONTRACT_QUANTITY
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setContractQuantity(BigDecimal contractQuantity) {
        this.contractQuantity = contractQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.CONTRACT_AMOUNT
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.CONTRACT_AMOUNT
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public BigDecimal getContractAmount() {
        return contractAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.CONTRACT_AMOUNT
     *
     * @param contractAmount the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.CONTRACT_AMOUNT
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setContractAmount(BigDecimal contractAmount) {
        this.contractAmount = contractAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.STRNO
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.STRNO
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public String getStrno() {
        return strno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.STRNO
     *
     * @param strno the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.STRNO
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setStrno(String strno) {
        this.strno = strno == null ? null : strno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ROW_NO
     *
     * @return the value of EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ROW_NO
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public Integer getRowNo() {
        return rowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ROW_NO
     *
     * @param rowNo the value for EPSS.ES_ITEM_STL_SUBCTT_ENG_P.ROW_NO
     *
     * @mbggenerated Fri Jul 04 13:14:27 CST 2014
     */
    public void setRowNo(Integer rowNo) {
        this.rowNo = rowNo;
    }
}