package epss.repository.model;

public class FlowCtrlHis {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_ctrl_his.PKID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_ctrl_his.INFO_TYPE
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String infoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_ctrl_his.INFO_PKID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String infoPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_ctrl_his.INFO_ID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String infoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_ctrl_his.INFO_NAME
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String infoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_ctrl_his.PERIOD_NO
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String periodNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_ctrl_his.FLOW_STATUS
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String flowStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_ctrl_his.FLOW_STATUS_REASON
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String flowStatusReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_ctrl_his.CREATED_BY
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_ctrl_his.CREATED_BY_NAME
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String createdByName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_ctrl_his.CREATED_TIME
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_ctrl_his.REMARK
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_ctrl_his.OPER_TYPE
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String operType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_ctrl_his.ARCHIVED_FLAG
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String archivedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_ctrl_his.TID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_ctrl_his.PKID
     *
     * @return the value of flow_ctrl_his.PKID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_ctrl_his.PKID
     *
     * @param pkid the value for flow_ctrl_his.PKID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_ctrl_his.INFO_TYPE
     *
     * @return the value of flow_ctrl_his.INFO_TYPE
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getInfoType() {
        return infoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_ctrl_his.INFO_TYPE
     *
     * @param infoType the value for flow_ctrl_his.INFO_TYPE
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setInfoType(String infoType) {
        this.infoType = infoType == null ? null : infoType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_ctrl_his.INFO_PKID
     *
     * @return the value of flow_ctrl_his.INFO_PKID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getInfoPkid() {
        return infoPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_ctrl_his.INFO_PKID
     *
     * @param infoPkid the value for flow_ctrl_his.INFO_PKID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setInfoPkid(String infoPkid) {
        this.infoPkid = infoPkid == null ? null : infoPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_ctrl_his.INFO_ID
     *
     * @return the value of flow_ctrl_his.INFO_ID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getInfoId() {
        return infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_ctrl_his.INFO_ID
     *
     * @param infoId the value for flow_ctrl_his.INFO_ID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setInfoId(String infoId) {
        this.infoId = infoId == null ? null : infoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_ctrl_his.INFO_NAME
     *
     * @return the value of flow_ctrl_his.INFO_NAME
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getInfoName() {
        return infoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_ctrl_his.INFO_NAME
     *
     * @param infoName the value for flow_ctrl_his.INFO_NAME
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setInfoName(String infoName) {
        this.infoName = infoName == null ? null : infoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_ctrl_his.PERIOD_NO
     *
     * @return the value of flow_ctrl_his.PERIOD_NO
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getPeriodNo() {
        return periodNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_ctrl_his.PERIOD_NO
     *
     * @param periodNo the value for flow_ctrl_his.PERIOD_NO
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setPeriodNo(String periodNo) {
        this.periodNo = periodNo == null ? null : periodNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_ctrl_his.FLOW_STATUS
     *
     * @return the value of flow_ctrl_his.FLOW_STATUS
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getFlowStatus() {
        return flowStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_ctrl_his.FLOW_STATUS
     *
     * @param flowStatus the value for flow_ctrl_his.FLOW_STATUS
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setFlowStatus(String flowStatus) {
        this.flowStatus = flowStatus == null ? null : flowStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_ctrl_his.FLOW_STATUS_REASON
     *
     * @return the value of flow_ctrl_his.FLOW_STATUS_REASON
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getFlowStatusReason() {
        return flowStatusReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_ctrl_his.FLOW_STATUS_REASON
     *
     * @param flowStatusReason the value for flow_ctrl_his.FLOW_STATUS_REASON
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setFlowStatusReason(String flowStatusReason) {
        this.flowStatusReason = flowStatusReason == null ? null : flowStatusReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_ctrl_his.CREATED_BY
     *
     * @return the value of flow_ctrl_his.CREATED_BY
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_ctrl_his.CREATED_BY
     *
     * @param createdBy the value for flow_ctrl_his.CREATED_BY
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_ctrl_his.CREATED_BY_NAME
     *
     * @return the value of flow_ctrl_his.CREATED_BY_NAME
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getCreatedByName() {
        return createdByName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_ctrl_his.CREATED_BY_NAME
     *
     * @param createdByName the value for flow_ctrl_his.CREATED_BY_NAME
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setCreatedByName(String createdByName) {
        this.createdByName = createdByName == null ? null : createdByName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_ctrl_his.CREATED_TIME
     *
     * @return the value of flow_ctrl_his.CREATED_TIME
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_ctrl_his.CREATED_TIME
     *
     * @param createdTime the value for flow_ctrl_his.CREATED_TIME
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime == null ? null : createdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_ctrl_his.REMARK
     *
     * @return the value of flow_ctrl_his.REMARK
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_ctrl_his.REMARK
     *
     * @param remark the value for flow_ctrl_his.REMARK
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_ctrl_his.OPER_TYPE
     *
     * @return the value of flow_ctrl_his.OPER_TYPE
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getOperType() {
        return operType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_ctrl_his.OPER_TYPE
     *
     * @param operType the value for flow_ctrl_his.OPER_TYPE
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setOperType(String operType) {
        this.operType = operType == null ? null : operType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_ctrl_his.ARCHIVED_FLAG
     *
     * @return the value of flow_ctrl_his.ARCHIVED_FLAG
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getArchivedFlag() {
        return archivedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_ctrl_his.ARCHIVED_FLAG
     *
     * @param archivedFlag the value for flow_ctrl_his.ARCHIVED_FLAG
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setArchivedFlag(String archivedFlag) {
        this.archivedFlag = archivedFlag == null ? null : archivedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_ctrl_his.TID
     *
     * @return the value of flow_ctrl_his.TID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_ctrl_his.TID
     *
     * @param tid the value for flow_ctrl_his.TID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }
}