package epss.repository.model;

import java.math.BigDecimal;

public class ProgStlItemTkMea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prog_stl_item_tk_mea.PKID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prog_stl_item_tk_mea.PERIOD_NO
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String periodNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prog_stl_item_tk_mea.TKCTT_PKID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String tkcttPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prog_stl_item_tk_mea.TKCTT_ITEM_PKID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String tkcttItemPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prog_stl_item_tk_mea.BEGIN_TO_CURRENT_PERIOD_QTY
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private BigDecimal beginToCurrentPeriodQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prog_stl_item_tk_mea.CURRENT_PERIOD_QTY
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private BigDecimal currentPeriodQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prog_stl_item_tk_mea.M_PURCHASE_UNIT_PRICE
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private BigDecimal mPurchaseUnitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prog_stl_item_tk_mea.ARCHIVED_FLAG
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String archivedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prog_stl_item_tk_mea.CREATED_BY
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prog_stl_item_tk_mea.CREATED_TIME
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prog_stl_item_tk_mea.LAST_UPD_BY
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prog_stl_item_tk_mea.LAST_UPD_TIME
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String lastUpdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prog_stl_item_tk_mea.REC_VERSION
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private Integer recVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prog_stl_item_tk_mea.PKID
     *
     * @return the value of prog_stl_item_tk_mea.PKID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prog_stl_item_tk_mea.PKID
     *
     * @param pkid the value for prog_stl_item_tk_mea.PKID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prog_stl_item_tk_mea.PERIOD_NO
     *
     * @return the value of prog_stl_item_tk_mea.PERIOD_NO
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getPeriodNo() {
        return periodNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prog_stl_item_tk_mea.PERIOD_NO
     *
     * @param periodNo the value for prog_stl_item_tk_mea.PERIOD_NO
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setPeriodNo(String periodNo) {
        this.periodNo = periodNo == null ? null : periodNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prog_stl_item_tk_mea.TKCTT_PKID
     *
     * @return the value of prog_stl_item_tk_mea.TKCTT_PKID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getTkcttPkid() {
        return tkcttPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prog_stl_item_tk_mea.TKCTT_PKID
     *
     * @param tkcttPkid the value for prog_stl_item_tk_mea.TKCTT_PKID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setTkcttPkid(String tkcttPkid) {
        this.tkcttPkid = tkcttPkid == null ? null : tkcttPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prog_stl_item_tk_mea.TKCTT_ITEM_PKID
     *
     * @return the value of prog_stl_item_tk_mea.TKCTT_ITEM_PKID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getTkcttItemPkid() {
        return tkcttItemPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prog_stl_item_tk_mea.TKCTT_ITEM_PKID
     *
     * @param tkcttItemPkid the value for prog_stl_item_tk_mea.TKCTT_ITEM_PKID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setTkcttItemPkid(String tkcttItemPkid) {
        this.tkcttItemPkid = tkcttItemPkid == null ? null : tkcttItemPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prog_stl_item_tk_mea.BEGIN_TO_CURRENT_PERIOD_QTY
     *
     * @return the value of prog_stl_item_tk_mea.BEGIN_TO_CURRENT_PERIOD_QTY
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public BigDecimal getBeginToCurrentPeriodQty() {
        return beginToCurrentPeriodQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prog_stl_item_tk_mea.BEGIN_TO_CURRENT_PERIOD_QTY
     *
     * @param beginToCurrentPeriodQty the value for prog_stl_item_tk_mea.BEGIN_TO_CURRENT_PERIOD_QTY
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setBeginToCurrentPeriodQty(BigDecimal beginToCurrentPeriodQty) {
        this.beginToCurrentPeriodQty = beginToCurrentPeriodQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prog_stl_item_tk_mea.CURRENT_PERIOD_QTY
     *
     * @return the value of prog_stl_item_tk_mea.CURRENT_PERIOD_QTY
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public BigDecimal getCurrentPeriodQty() {
        return currentPeriodQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prog_stl_item_tk_mea.CURRENT_PERIOD_QTY
     *
     * @param currentPeriodQty the value for prog_stl_item_tk_mea.CURRENT_PERIOD_QTY
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setCurrentPeriodQty(BigDecimal currentPeriodQty) {
        this.currentPeriodQty = currentPeriodQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prog_stl_item_tk_mea.M_PURCHASE_UNIT_PRICE
     *
     * @return the value of prog_stl_item_tk_mea.M_PURCHASE_UNIT_PRICE
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public BigDecimal getmPurchaseUnitPrice() {
        return mPurchaseUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prog_stl_item_tk_mea.M_PURCHASE_UNIT_PRICE
     *
     * @param mPurchaseUnitPrice the value for prog_stl_item_tk_mea.M_PURCHASE_UNIT_PRICE
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setmPurchaseUnitPrice(BigDecimal mPurchaseUnitPrice) {
        this.mPurchaseUnitPrice = mPurchaseUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prog_stl_item_tk_mea.ARCHIVED_FLAG
     *
     * @return the value of prog_stl_item_tk_mea.ARCHIVED_FLAG
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getArchivedFlag() {
        return archivedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prog_stl_item_tk_mea.ARCHIVED_FLAG
     *
     * @param archivedFlag the value for prog_stl_item_tk_mea.ARCHIVED_FLAG
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setArchivedFlag(String archivedFlag) {
        this.archivedFlag = archivedFlag == null ? null : archivedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prog_stl_item_tk_mea.CREATED_BY
     *
     * @return the value of prog_stl_item_tk_mea.CREATED_BY
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prog_stl_item_tk_mea.CREATED_BY
     *
     * @param createdBy the value for prog_stl_item_tk_mea.CREATED_BY
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prog_stl_item_tk_mea.CREATED_TIME
     *
     * @return the value of prog_stl_item_tk_mea.CREATED_TIME
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prog_stl_item_tk_mea.CREATED_TIME
     *
     * @param createdTime the value for prog_stl_item_tk_mea.CREATED_TIME
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime == null ? null : createdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prog_stl_item_tk_mea.LAST_UPD_BY
     *
     * @return the value of prog_stl_item_tk_mea.LAST_UPD_BY
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prog_stl_item_tk_mea.LAST_UPD_BY
     *
     * @param lastUpdBy the value for prog_stl_item_tk_mea.LAST_UPD_BY
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prog_stl_item_tk_mea.LAST_UPD_TIME
     *
     * @return the value of prog_stl_item_tk_mea.LAST_UPD_TIME
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prog_stl_item_tk_mea.LAST_UPD_TIME
     *
     * @param lastUpdTime the value for prog_stl_item_tk_mea.LAST_UPD_TIME
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setLastUpdTime(String lastUpdTime) {
        this.lastUpdTime = lastUpdTime == null ? null : lastUpdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prog_stl_item_tk_mea.REC_VERSION
     *
     * @return the value of prog_stl_item_tk_mea.REC_VERSION
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public Integer getRecVersion() {
        return recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prog_stl_item_tk_mea.REC_VERSION
     *
     * @param recVersion the value for prog_stl_item_tk_mea.REC_VERSION
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setRecVersion(Integer recVersion) {
        this.recVersion = recVersion;
    }
}