package epss.repository.model;

public class PtenudetailKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptenudetail.ENUITEMVALUE
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String enuitemvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptenudetail.ENUTYPE
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String enutype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptenudetail.ENUITEMVALUE
     *
     * @return the value of ptenudetail.ENUITEMVALUE
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getEnuitemvalue() {
        return enuitemvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptenudetail.ENUITEMVALUE
     *
     * @param enuitemvalue the value for ptenudetail.ENUITEMVALUE
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setEnuitemvalue(String enuitemvalue) {
        this.enuitemvalue = enuitemvalue == null ? null : enuitemvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptenudetail.ENUTYPE
     *
     * @return the value of ptenudetail.ENUTYPE
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getEnutype() {
        return enutype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptenudetail.ENUTYPE
     *
     * @param enutype the value for ptenudetail.ENUTYPE
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setEnutype(String enutype) {
        this.enutype = enutype == null ? null : enutype.trim();
    }
}