package epss.repository.model;

public class Ptenudetail extends PtenudetailKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptenudetail.ENUITEMLABEL
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String enuitemlabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptenudetail.ENUITEMDESC
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String enuitemdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptenudetail.DISPNO
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private Integer dispno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ptenudetail.ENUITEMEXPAND
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String enuitemexpand;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptenudetail.ENUITEMLABEL
     *
     * @return the value of ptenudetail.ENUITEMLABEL
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getEnuitemlabel() {
        return enuitemlabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptenudetail.ENUITEMLABEL
     *
     * @param enuitemlabel the value for ptenudetail.ENUITEMLABEL
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setEnuitemlabel(String enuitemlabel) {
        this.enuitemlabel = enuitemlabel == null ? null : enuitemlabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptenudetail.ENUITEMDESC
     *
     * @return the value of ptenudetail.ENUITEMDESC
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getEnuitemdesc() {
        return enuitemdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptenudetail.ENUITEMDESC
     *
     * @param enuitemdesc the value for ptenudetail.ENUITEMDESC
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setEnuitemdesc(String enuitemdesc) {
        this.enuitemdesc = enuitemdesc == null ? null : enuitemdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptenudetail.DISPNO
     *
     * @return the value of ptenudetail.DISPNO
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public Integer getDispno() {
        return dispno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptenudetail.DISPNO
     *
     * @param dispno the value for ptenudetail.DISPNO
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setDispno(Integer dispno) {
        this.dispno = dispno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ptenudetail.ENUITEMEXPAND
     *
     * @return the value of ptenudetail.ENUITEMEXPAND
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getEnuitemexpand() {
        return enuitemexpand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ptenudetail.ENUITEMEXPAND
     *
     * @param enuitemexpand the value for ptenudetail.ENUITEMEXPAND
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setEnuitemexpand(String enuitemexpand) {
        this.enuitemexpand = enuitemexpand == null ? null : enuitemexpand.trim();
    }
}