package epss.repository.model;

public class Tidkeys {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tidkeys.PKID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tidkeys.TID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tidkeys.KEY1
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    private String key1;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tidkeys.PKID
     *
     * @return the value of tidkeys.PKID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tidkeys.PKID
     *
     * @param pkid the value for tidkeys.PKID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tidkeys.TID
     *
     * @return the value of tidkeys.TID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tidkeys.TID
     *
     * @param tid the value for tidkeys.TID
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tidkeys.KEY1
     *
     * @return the value of tidkeys.KEY1
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public String getKey1() {
        return key1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tidkeys.KEY1
     *
     * @param key1 the value for tidkeys.KEY1
     *
     * @mbggenerated Wed Oct 08 14:42:56 CST 2014
     */
    public void setKey1(String key1) {
        this.key1 = key1 == null ? null : key1.trim();
    }
}