package skyline.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import skyline.repository.model.Ptroleres;
import skyline.repository.model.PtroleresExample;

public interface PtroleresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTROLERES
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    int countByExample(PtroleresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTROLERES
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    int deleteByExample(PtroleresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTROLERES
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    int insert(Ptroleres record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTROLERES
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    int insertSelective(Ptroleres record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTROLERES
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    List<Ptroleres> selectByExample(PtroleresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTROLERES
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    int updateByExampleSelective(@Param("record") Ptroleres record, @Param("example") PtroleresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTROLERES
     *
     * @mbggenerated Fri Aug 22 09:11:21 CST 2014
     */
    int updateByExample(@Param("record") Ptroleres record, @Param("example") PtroleresExample example);
}