package epss.repository.model;

public class EsInitPower extends EsInitPowerKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_INIT_POWER.STATUS_FLAG
     *
     * @mbggenerated Fri Apr 25 17:26:31 CST 2014
     */
    private String statusFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_INIT_POWER.PRE_STATUS_FLAG
     *
     * @mbggenerated Fri Apr 25 17:26:31 CST 2014
     */
    private String preStatusFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_INIT_POWER.CREATED_BY
     *
     * @mbggenerated Fri Apr 25 17:26:31 CST 2014
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_INIT_POWER.CREATED_DATE
     *
     * @mbggenerated Fri Apr 25 17:26:31 CST 2014
     */
    private String createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_INIT_POWER.LAST_UPD_BY
     *
     * @mbggenerated Fri Apr 25 17:26:31 CST 2014
     */
    private String lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_INIT_POWER.LAST_UPD_DATE
     *
     * @mbggenerated Fri Apr 25 17:26:31 CST 2014
     */
    private String lastUpdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_INIT_POWER.SPARE_FIELD
     *
     * @mbggenerated Fri Apr 25 17:26:31 CST 2014
     */
    private String spareField;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_INIT_POWER.STATUS_FLAG
     *
     * @return the value of EPSS.ES_INIT_POWER.STATUS_FLAG
     *
     * @mbggenerated Fri Apr 25 17:26:31 CST 2014
     */
    public String getStatusFlag() {
        return statusFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_INIT_POWER.STATUS_FLAG
     *
     * @param statusFlag the value for EPSS.ES_INIT_POWER.STATUS_FLAG
     *
     * @mbggenerated Fri Apr 25 17:26:31 CST 2014
     */
    public void setStatusFlag(String statusFlag) {
        this.statusFlag = statusFlag == null ? null : statusFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_INIT_POWER.PRE_STATUS_FLAG
     *
     * @return the value of EPSS.ES_INIT_POWER.PRE_STATUS_FLAG
     *
     * @mbggenerated Fri Apr 25 17:26:31 CST 2014
     */
    public String getPreStatusFlag() {
        return preStatusFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_INIT_POWER.PRE_STATUS_FLAG
     *
     * @param preStatusFlag the value for EPSS.ES_INIT_POWER.PRE_STATUS_FLAG
     *
     * @mbggenerated Fri Apr 25 17:26:31 CST 2014
     */
    public void setPreStatusFlag(String preStatusFlag) {
        this.preStatusFlag = preStatusFlag == null ? null : preStatusFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_INIT_POWER.CREATED_BY
     *
     * @return the value of EPSS.ES_INIT_POWER.CREATED_BY
     *
     * @mbggenerated Fri Apr 25 17:26:31 CST 2014
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_INIT_POWER.CREATED_BY
     *
     * @param createdBy the value for EPSS.ES_INIT_POWER.CREATED_BY
     *
     * @mbggenerated Fri Apr 25 17:26:31 CST 2014
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_INIT_POWER.CREATED_DATE
     *
     * @return the value of EPSS.ES_INIT_POWER.CREATED_DATE
     *
     * @mbggenerated Fri Apr 25 17:26:31 CST 2014
     */
    public String getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_INIT_POWER.CREATED_DATE
     *
     * @param createdDate the value for EPSS.ES_INIT_POWER.CREATED_DATE
     *
     * @mbggenerated Fri Apr 25 17:26:31 CST 2014
     */
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate == null ? null : createdDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_INIT_POWER.LAST_UPD_BY
     *
     * @return the value of EPSS.ES_INIT_POWER.LAST_UPD_BY
     *
     * @mbggenerated Fri Apr 25 17:26:31 CST 2014
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_INIT_POWER.LAST_UPD_BY
     *
     * @param lastUpdBy the value for EPSS.ES_INIT_POWER.LAST_UPD_BY
     *
     * @mbggenerated Fri Apr 25 17:26:31 CST 2014
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_INIT_POWER.LAST_UPD_DATE
     *
     * @return the value of EPSS.ES_INIT_POWER.LAST_UPD_DATE
     *
     * @mbggenerated Fri Apr 25 17:26:31 CST 2014
     */
    public String getLastUpdDate() {
        return lastUpdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_INIT_POWER.LAST_UPD_DATE
     *
     * @param lastUpdDate the value for EPSS.ES_INIT_POWER.LAST_UPD_DATE
     *
     * @mbggenerated Fri Apr 25 17:26:31 CST 2014
     */
    public void setLastUpdDate(String lastUpdDate) {
        this.lastUpdDate = lastUpdDate == null ? null : lastUpdDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_INIT_POWER.SPARE_FIELD
     *
     * @return the value of EPSS.ES_INIT_POWER.SPARE_FIELD
     *
     * @mbggenerated Fri Apr 25 17:26:31 CST 2014
     */
    public String getSpareField() {
        return spareField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_INIT_POWER.SPARE_FIELD
     *
     * @param spareField the value for EPSS.ES_INIT_POWER.SPARE_FIELD
     *
     * @mbggenerated Fri Apr 25 17:26:31 CST 2014
     */
    public void setSpareField(String spareField) {
        this.spareField = spareField == null ? null : spareField.trim();
    }
}