package epss.repository.model;

public class EsInitPowerHisKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_INIT_POWER_HIS.POWER_TYPE
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    private String powerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_INIT_POWER_HIS.POWER_PKID
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    private String powerPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.ES_INIT_POWER_HIS.PERIOD_NO
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    private String periodNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_INIT_POWER_HIS.POWER_TYPE
     *
     * @return the value of EPSS.ES_INIT_POWER_HIS.POWER_TYPE
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    public String getPowerType() {
        return powerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_INIT_POWER_HIS.POWER_TYPE
     *
     * @param powerType the value for EPSS.ES_INIT_POWER_HIS.POWER_TYPE
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    public void setPowerType(String powerType) {
        this.powerType = powerType == null ? null : powerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_INIT_POWER_HIS.POWER_PKID
     *
     * @return the value of EPSS.ES_INIT_POWER_HIS.POWER_PKID
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    public String getPowerPkid() {
        return powerPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_INIT_POWER_HIS.POWER_PKID
     *
     * @param powerPkid the value for EPSS.ES_INIT_POWER_HIS.POWER_PKID
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    public void setPowerPkid(String powerPkid) {
        this.powerPkid = powerPkid == null ? null : powerPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.ES_INIT_POWER_HIS.PERIOD_NO
     *
     * @return the value of EPSS.ES_INIT_POWER_HIS.PERIOD_NO
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    public String getPeriodNo() {
        return periodNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.ES_INIT_POWER_HIS.PERIOD_NO
     *
     * @param periodNo the value for EPSS.ES_INIT_POWER_HIS.PERIOD_NO
     *
     * @mbggenerated Tue Jul 16 10:21:29 CST 2013
     */
    public void setPeriodNo(String periodNo) {
        this.periodNo = periodNo == null ? null : periodNo.trim();
    }
}