package epss.repository.dao;

import epss.repository.model.AllTabColumns;
import epss.repository.model.AllTabColumnsExample;
import epss.repository.model.AllTabColumnsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AllTabColumnsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALL_TAB_COLUMNS
     *
     * @mbggenerated Fri Apr 19 17:08:30 CST 2013
     */
    int countByExample(AllTabColumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALL_TAB_COLUMNS
     *
     * @mbggenerated Fri Apr 19 17:08:30 CST 2013
     */
    int deleteByExample(AllTabColumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALL_TAB_COLUMNS
     *
     * @mbggenerated Fri Apr 19 17:08:30 CST 2013
     */
    int insert(AllTabColumnsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALL_TAB_COLUMNS
     *
     * @mbggenerated Fri Apr 19 17:08:30 CST 2013
     */
    int insertSelective(AllTabColumnsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALL_TAB_COLUMNS
     *
     * @mbggenerated Fri Apr 19 17:08:30 CST 2013
     */
    List<AllTabColumnsWithBLOBs> selectByExampleWithBLOBs(AllTabColumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALL_TAB_COLUMNS
     *
     * @mbggenerated Fri Apr 19 17:08:30 CST 2013
     */
    List<AllTabColumns> selectByExample(AllTabColumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALL_TAB_COLUMNS
     *
     * @mbggenerated Fri Apr 19 17:08:30 CST 2013
     */
    int updateByExampleSelective(@Param("record") AllTabColumnsWithBLOBs record, @Param("example") AllTabColumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALL_TAB_COLUMNS
     *
     * @mbggenerated Fri Apr 19 17:08:30 CST 2013
     */
    int updateByExampleWithBLOBs(@Param("record") AllTabColumnsWithBLOBs record, @Param("example") AllTabColumnsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ALL_TAB_COLUMNS
     *
     * @mbggenerated Fri Apr 19 17:08:30 CST 2013
     */
    int updateByExample(@Param("record") AllTabColumns record, @Param("example") AllTabColumnsExample example);
}