package epss.repository.dao;

import epss.repository.model.OperRes;
import epss.repository.model.OperResExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OperResMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper_res
     *
     * @mbggenerated Wed Jan 28 14:28:53 CST 2015
     */
    int countByExample(OperResExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper_res
     *
     * @mbggenerated Wed Jan 28 14:28:53 CST 2015
     */
    int deleteByExample(OperResExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper_res
     *
     * @mbggenerated Wed Jan 28 14:28:53 CST 2015
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper_res
     *
     * @mbggenerated Wed Jan 28 14:28:53 CST 2015
     */
    int insert(OperRes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper_res
     *
     * @mbggenerated Wed Jan 28 14:28:53 CST 2015
     */
    int insertSelective(OperRes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper_res
     *
     * @mbggenerated Wed Jan 28 14:28:53 CST 2015
     */
    List<OperRes> selectByExample(OperResExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper_res
     *
     * @mbggenerated Wed Jan 28 14:28:53 CST 2015
     */
    OperRes selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper_res
     *
     * @mbggenerated Wed Jan 28 14:28:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") OperRes record, @Param("example") OperResExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper_res
     *
     * @mbggenerated Wed Jan 28 14:28:53 CST 2015
     */
    int updateByExample(@Param("record") OperRes record, @Param("example") OperResExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper_res
     *
     * @mbggenerated Wed Jan 28 14:28:53 CST 2015
     */
    int updateByPrimaryKeySelective(OperRes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oper_res
     *
     * @mbggenerated Wed Jan 28 14:28:53 CST 2015
     */
    int updateByPrimaryKey(OperRes record);
}