package epss.repository.dao;

import epss.repository.model.ProgStlItemSubF;
import epss.repository.model.ProgStlItemSubFExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProgStlItemSubFMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prog_stl_item_sub_f
     *
     * @mbggenerated Wed Jan 28 14:28:53 CST 2015
     */
    int countByExample(ProgStlItemSubFExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prog_stl_item_sub_f
     *
     * @mbggenerated Wed Jan 28 14:28:53 CST 2015
     */
    int deleteByExample(ProgStlItemSubFExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prog_stl_item_sub_f
     *
     * @mbggenerated Wed Jan 28 14:28:53 CST 2015
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prog_stl_item_sub_f
     *
     * @mbggenerated Wed Jan 28 14:28:53 CST 2015
     */
    int insert(ProgStlItemSubF record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prog_stl_item_sub_f
     *
     * @mbggenerated Wed Jan 28 14:28:53 CST 2015
     */
    int insertSelective(ProgStlItemSubF record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prog_stl_item_sub_f
     *
     * @mbggenerated Wed Jan 28 14:28:53 CST 2015
     */
    List<ProgStlItemSubF> selectByExample(ProgStlItemSubFExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prog_stl_item_sub_f
     *
     * @mbggenerated Wed Jan 28 14:28:53 CST 2015
     */
    ProgStlItemSubF selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prog_stl_item_sub_f
     *
     * @mbggenerated Wed Jan 28 14:28:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") ProgStlItemSubF record, @Param("example") ProgStlItemSubFExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prog_stl_item_sub_f
     *
     * @mbggenerated Wed Jan 28 14:28:53 CST 2015
     */
    int updateByExample(@Param("record") ProgStlItemSubF record, @Param("example") ProgStlItemSubFExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prog_stl_item_sub_f
     *
     * @mbggenerated Wed Jan 28 14:28:53 CST 2015
     */
    int updateByPrimaryKeySelective(ProgStlItemSubF record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prog_stl_item_sub_f
     *
     * @mbggenerated Wed Jan 28 14:28:53 CST 2015
     */
    int updateByPrimaryKey(ProgStlItemSubF record);
}