package epss.repository.dao;

import epss.repository.model.ProgStlItemSubQ;
import epss.repository.model.ProgStlItemSubQExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProgStlItemSubQMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prog_stl_item_sub_q
     *
     * @mbggenerated Fri May 01 00:30:15 CST 2015
     */
    int countByExample(ProgStlItemSubQExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prog_stl_item_sub_q
     *
     * @mbggenerated Fri May 01 00:30:15 CST 2015
     */
    int deleteByExample(ProgStlItemSubQExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prog_stl_item_sub_q
     *
     * @mbggenerated Fri May 01 00:30:15 CST 2015
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prog_stl_item_sub_q
     *
     * @mbggenerated Fri May 01 00:30:15 CST 2015
     */
    int insert(ProgStlItemSubQ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prog_stl_item_sub_q
     *
     * @mbggenerated Fri May 01 00:30:15 CST 2015
     */
    int insertSelective(ProgStlItemSubQ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prog_stl_item_sub_q
     *
     * @mbggenerated Fri May 01 00:30:15 CST 2015
     */
    List<ProgStlItemSubQ> selectByExample(ProgStlItemSubQExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prog_stl_item_sub_q
     *
     * @mbggenerated Fri May 01 00:30:15 CST 2015
     */
    ProgStlItemSubQ selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prog_stl_item_sub_q
     *
     * @mbggenerated Fri May 01 00:30:15 CST 2015
     */
    int updateByExampleSelective(@Param("record") ProgStlItemSubQ record, @Param("example") ProgStlItemSubQExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prog_stl_item_sub_q
     *
     * @mbggenerated Fri May 01 00:30:15 CST 2015
     */
    int updateByExample(@Param("record") ProgStlItemSubQ record, @Param("example") ProgStlItemSubQExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prog_stl_item_sub_q
     *
     * @mbggenerated Fri May 01 00:30:15 CST 2015
     */
    int updateByPrimaryKeySelective(ProgStlItemSubQ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prog_stl_item_sub_q
     *
     * @mbggenerated Fri May 01 00:30:15 CST 2015
     */
    int updateByPrimaryKey(ProgStlItemSubQ record);
}