package epss.repository.dao;

import epss.repository.model.Ptlogicact;
import epss.repository.model.PtlogicactExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PtlogicactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptlogicact
     *
     * @mbggenerated Fri May 01 00:30:15 CST 2015
     */
    int countByExample(PtlogicactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptlogicact
     *
     * @mbggenerated Fri May 01 00:30:15 CST 2015
     */
    int deleteByExample(PtlogicactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptlogicact
     *
     * @mbggenerated Fri May 01 00:30:15 CST 2015
     */
    int insert(Ptlogicact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptlogicact
     *
     * @mbggenerated Fri May 01 00:30:15 CST 2015
     */
    int insertSelective(Ptlogicact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptlogicact
     *
     * @mbggenerated Fri May 01 00:30:15 CST 2015
     */
    List<Ptlogicact> selectByExample(PtlogicactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptlogicact
     *
     * @mbggenerated Fri May 01 00:30:15 CST 2015
     */
    int updateByExampleSelective(@Param("record") Ptlogicact record, @Param("example") PtlogicactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptlogicact
     *
     * @mbggenerated Fri May 01 00:30:15 CST 2015
     */
    int updateByExample(@Param("record") Ptlogicact record, @Param("example") PtlogicactExample example);
}