package epss.repository.dao;

import epss.repository.model.CttInfo;
import epss.repository.model.CttInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CttInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.CTT_INFO
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    int countByExample(CttInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.CTT_INFO
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    int deleteByExample(CttInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.CTT_INFO
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.CTT_INFO
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    int insert(CttInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.CTT_INFO
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    int insertSelective(CttInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.CTT_INFO
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    List<CttInfo> selectByExample(CttInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.CTT_INFO
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    CttInfo selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.CTT_INFO
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    int updateByExampleSelective(@Param("record") CttInfo record, @Param("example") CttInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.CTT_INFO
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    int updateByExample(@Param("record") CttInfo record, @Param("example") CttInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.CTT_INFO
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    int updateByPrimaryKeySelective(CttInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.CTT_INFO
     *
     * @mbggenerated Fri Sep 19 08:54:16 CST 2014
     */
    int updateByPrimaryKey(CttInfo record);
}