package epss.repository.dao;

import epss.repository.model.EsItemStlSubcttEngM;
import epss.repository.model.EsItemStlSubcttEngMExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EsItemStlSubcttEngMMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.ES_ITEM_STL_SUBCTT_ENG_M
     *
     * @mbggenerated Fri Sep 05 12:05:34 CST 2014
     */
    int countByExample(EsItemStlSubcttEngMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.ES_ITEM_STL_SUBCTT_ENG_M
     *
     * @mbggenerated Fri Sep 05 12:05:34 CST 2014
     */
    int deleteByExample(EsItemStlSubcttEngMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.ES_ITEM_STL_SUBCTT_ENG_M
     *
     * @mbggenerated Fri Sep 05 12:05:34 CST 2014
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.ES_ITEM_STL_SUBCTT_ENG_M
     *
     * @mbggenerated Fri Sep 05 12:05:34 CST 2014
     */
    int insert(EsItemStlSubcttEngM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.ES_ITEM_STL_SUBCTT_ENG_M
     *
     * @mbggenerated Fri Sep 05 12:05:34 CST 2014
     */
    int insertSelective(EsItemStlSubcttEngM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.ES_ITEM_STL_SUBCTT_ENG_M
     *
     * @mbggenerated Fri Sep 05 12:05:34 CST 2014
     */
    List<EsItemStlSubcttEngM> selectByExample(EsItemStlSubcttEngMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.ES_ITEM_STL_SUBCTT_ENG_M
     *
     * @mbggenerated Fri Sep 05 12:05:34 CST 2014
     */
    EsItemStlSubcttEngM selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.ES_ITEM_STL_SUBCTT_ENG_M
     *
     * @mbggenerated Fri Sep 05 12:05:34 CST 2014
     */
    int updateByExampleSelective(@Param("record") EsItemStlSubcttEngM record, @Param("example") EsItemStlSubcttEngMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.ES_ITEM_STL_SUBCTT_ENG_M
     *
     * @mbggenerated Fri Sep 05 12:05:34 CST 2014
     */
    int updateByExample(@Param("record") EsItemStlSubcttEngM record, @Param("example") EsItemStlSubcttEngMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.ES_ITEM_STL_SUBCTT_ENG_M
     *
     * @mbggenerated Fri Sep 05 12:05:34 CST 2014
     */
    int updateByPrimaryKeySelective(EsItemStlSubcttEngM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.ES_ITEM_STL_SUBCTT_ENG_M
     *
     * @mbggenerated Fri Sep 05 12:05:34 CST 2014
     */
    int updateByPrimaryKey(EsItemStlSubcttEngM record);
}