package epss.repository.model;

import java.util.ArrayList;
import java.util.List;

public class OperResTaskExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EPSS.OPER_RES_TASK
     *
     * @mbggenerated Wed Sep 03 10:18:28 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EPSS.OPER_RES_TASK
     *
     * @mbggenerated Wed Sep 03 10:18:28 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table EPSS.OPER_RES_TASK
     *
     * @mbggenerated Wed Sep 03 10:18:28 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.OPER_RES_TASK
     *
     * @mbggenerated Wed Sep 03 10:18:28 CST 2014
     */
    public OperResTaskExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.OPER_RES_TASK
     *
     * @mbggenerated Wed Sep 03 10:18:28 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.OPER_RES_TASK
     *
     * @mbggenerated Wed Sep 03 10:18:28 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.OPER_RES_TASK
     *
     * @mbggenerated Wed Sep 03 10:18:28 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.OPER_RES_TASK
     *
     * @mbggenerated Wed Sep 03 10:18:28 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.OPER_RES_TASK
     *
     * @mbggenerated Wed Sep 03 10:18:28 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.OPER_RES_TASK
     *
     * @mbggenerated Wed Sep 03 10:18:28 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.OPER_RES_TASK
     *
     * @mbggenerated Wed Sep 03 10:18:28 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.OPER_RES_TASK
     *
     * @mbggenerated Wed Sep 03 10:18:28 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.OPER_RES_TASK
     *
     * @mbggenerated Wed Sep 03 10:18:28 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EPSS.OPER_RES_TASK
     *
     * @mbggenerated Wed Sep 03 10:18:28 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table EPSS.OPER_RES_TASK
     *
     * @mbggenerated Wed Sep 03 10:18:28 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andOperPkidIsNull() {
            addCriterion("OPER_PKID is null");
            return (Criteria) this;
        }

        public Criteria andOperPkidIsNotNull() {
            addCriterion("OPER_PKID is not null");
            return (Criteria) this;
        }

        public Criteria andOperPkidEqualTo(String value) {
            addCriterion("OPER_PKID =", value, "operPkid");
            return (Criteria) this;
        }

        public Criteria andOperPkidNotEqualTo(String value) {
            addCriterion("OPER_PKID <>", value, "operPkid");
            return (Criteria) this;
        }

        public Criteria andOperPkidGreaterThan(String value) {
            addCriterion("OPER_PKID >", value, "operPkid");
            return (Criteria) this;
        }

        public Criteria andOperPkidGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_PKID >=", value, "operPkid");
            return (Criteria) this;
        }

        public Criteria andOperPkidLessThan(String value) {
            addCriterion("OPER_PKID <", value, "operPkid");
            return (Criteria) this;
        }

        public Criteria andOperPkidLessThanOrEqualTo(String value) {
            addCriterion("OPER_PKID <=", value, "operPkid");
            return (Criteria) this;
        }

        public Criteria andOperPkidLike(String value) {
            addCriterion("OPER_PKID like", value, "operPkid");
            return (Criteria) this;
        }

        public Criteria andOperPkidNotLike(String value) {
            addCriterion("OPER_PKID not like", value, "operPkid");
            return (Criteria) this;
        }

        public Criteria andOperPkidIn(List<String> values) {
            addCriterion("OPER_PKID in", values, "operPkid");
            return (Criteria) this;
        }

        public Criteria andOperPkidNotIn(List<String> values) {
            addCriterion("OPER_PKID not in", values, "operPkid");
            return (Criteria) this;
        }

        public Criteria andOperPkidBetween(String value1, String value2) {
            addCriterion("OPER_PKID between", value1, value2, "operPkid");
            return (Criteria) this;
        }

        public Criteria andOperPkidNotBetween(String value1, String value2) {
            addCriterion("OPER_PKID not between", value1, value2, "operPkid");
            return (Criteria) this;
        }

        public Criteria andInfoTypeIsNull() {
            addCriterion("INFO_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andInfoTypeIsNotNull() {
            addCriterion("INFO_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andInfoTypeEqualTo(String value) {
            addCriterion("INFO_TYPE =", value, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeNotEqualTo(String value) {
            addCriterion("INFO_TYPE <>", value, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeGreaterThan(String value) {
            addCriterion("INFO_TYPE >", value, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeGreaterThanOrEqualTo(String value) {
            addCriterion("INFO_TYPE >=", value, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeLessThan(String value) {
            addCriterion("INFO_TYPE <", value, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeLessThanOrEqualTo(String value) {
            addCriterion("INFO_TYPE <=", value, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeLike(String value) {
            addCriterion("INFO_TYPE like", value, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeNotLike(String value) {
            addCriterion("INFO_TYPE not like", value, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeIn(List<String> values) {
            addCriterion("INFO_TYPE in", values, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeNotIn(List<String> values) {
            addCriterion("INFO_TYPE not in", values, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeBetween(String value1, String value2) {
            addCriterion("INFO_TYPE between", value1, value2, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoTypeNotBetween(String value1, String value2) {
            addCriterion("INFO_TYPE not between", value1, value2, "infoType");
            return (Criteria) this;
        }

        public Criteria andInfoPkidIsNull() {
            addCriterion("INFO_PKID is null");
            return (Criteria) this;
        }

        public Criteria andInfoPkidIsNotNull() {
            addCriterion("INFO_PKID is not null");
            return (Criteria) this;
        }

        public Criteria andInfoPkidEqualTo(String value) {
            addCriterion("INFO_PKID =", value, "infoPkid");
            return (Criteria) this;
        }

        public Criteria andInfoPkidNotEqualTo(String value) {
            addCriterion("INFO_PKID <>", value, "infoPkid");
            return (Criteria) this;
        }

        public Criteria andInfoPkidGreaterThan(String value) {
            addCriterion("INFO_PKID >", value, "infoPkid");
            return (Criteria) this;
        }

        public Criteria andInfoPkidGreaterThanOrEqualTo(String value) {
            addCriterion("INFO_PKID >=", value, "infoPkid");
            return (Criteria) this;
        }

        public Criteria andInfoPkidLessThan(String value) {
            addCriterion("INFO_PKID <", value, "infoPkid");
            return (Criteria) this;
        }

        public Criteria andInfoPkidLessThanOrEqualTo(String value) {
            addCriterion("INFO_PKID <=", value, "infoPkid");
            return (Criteria) this;
        }

        public Criteria andInfoPkidLike(String value) {
            addCriterion("INFO_PKID like", value, "infoPkid");
            return (Criteria) this;
        }

        public Criteria andInfoPkidNotLike(String value) {
            addCriterion("INFO_PKID not like", value, "infoPkid");
            return (Criteria) this;
        }

        public Criteria andInfoPkidIn(List<String> values) {
            addCriterion("INFO_PKID in", values, "infoPkid");
            return (Criteria) this;
        }

        public Criteria andInfoPkidNotIn(List<String> values) {
            addCriterion("INFO_PKID not in", values, "infoPkid");
            return (Criteria) this;
        }

        public Criteria andInfoPkidBetween(String value1, String value2) {
            addCriterion("INFO_PKID between", value1, value2, "infoPkid");
            return (Criteria) this;
        }

        public Criteria andInfoPkidNotBetween(String value1, String value2) {
            addCriterion("INFO_PKID not between", value1, value2, "infoPkid");
            return (Criteria) this;
        }

        public Criteria andInfoNameIsNull() {
            addCriterion("INFO_NAME is null");
            return (Criteria) this;
        }

        public Criteria andInfoNameIsNotNull() {
            addCriterion("INFO_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andInfoNameEqualTo(String value) {
            addCriterion("INFO_NAME =", value, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameNotEqualTo(String value) {
            addCriterion("INFO_NAME <>", value, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameGreaterThan(String value) {
            addCriterion("INFO_NAME >", value, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameGreaterThanOrEqualTo(String value) {
            addCriterion("INFO_NAME >=", value, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameLessThan(String value) {
            addCriterion("INFO_NAME <", value, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameLessThanOrEqualTo(String value) {
            addCriterion("INFO_NAME <=", value, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameLike(String value) {
            addCriterion("INFO_NAME like", value, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameNotLike(String value) {
            addCriterion("INFO_NAME not like", value, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameIn(List<String> values) {
            addCriterion("INFO_NAME in", values, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameNotIn(List<String> values) {
            addCriterion("INFO_NAME not in", values, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameBetween(String value1, String value2) {
            addCriterion("INFO_NAME between", value1, value2, "infoName");
            return (Criteria) this;
        }

        public Criteria andInfoNameNotBetween(String value1, String value2) {
            addCriterion("INFO_NAME not between", value1, value2, "infoName");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("CREATED_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("CREATED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("CREATED_BY =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("CREATED_BY <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("CREATED_BY >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("CREATED_BY >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("CREATED_BY <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("CREATED_BY <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("CREATED_BY like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("CREATED_BY not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("CREATED_BY in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("CREATED_BY not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("CREATED_BY between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("CREATED_BY not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("CREATED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("CREATED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(String value) {
            addCriterion("CREATED_TIME =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(String value) {
            addCriterion("CREATED_TIME <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(String value) {
            addCriterion("CREATED_TIME >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(String value) {
            addCriterion("CREATED_TIME >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(String value) {
            addCriterion("CREATED_TIME <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(String value) {
            addCriterion("CREATED_TIME <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLike(String value) {
            addCriterion("CREATED_TIME like", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotLike(String value) {
            addCriterion("CREATED_TIME not like", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<String> values) {
            addCriterion("CREATED_TIME in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<String> values) {
            addCriterion("CREATED_TIME not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(String value1, String value2) {
            addCriterion("CREATED_TIME between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(String value1, String value2) {
            addCriterion("CREATED_TIME not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdByIsNull() {
            addCriterion("LAST_UPD_BY is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdByIsNotNull() {
            addCriterion("LAST_UPD_BY is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdByEqualTo(String value) {
            addCriterion("LAST_UPD_BY =", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotEqualTo(String value) {
            addCriterion("LAST_UPD_BY <>", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByGreaterThan(String value) {
            addCriterion("LAST_UPD_BY >", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_UPD_BY >=", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByLessThan(String value) {
            addCriterion("LAST_UPD_BY <", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByLessThanOrEqualTo(String value) {
            addCriterion("LAST_UPD_BY <=", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByLike(String value) {
            addCriterion("LAST_UPD_BY like", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotLike(String value) {
            addCriterion("LAST_UPD_BY not like", value, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByIn(List<String> values) {
            addCriterion("LAST_UPD_BY in", values, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotIn(List<String> values) {
            addCriterion("LAST_UPD_BY not in", values, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByBetween(String value1, String value2) {
            addCriterion("LAST_UPD_BY between", value1, value2, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdByNotBetween(String value1, String value2) {
            addCriterion("LAST_UPD_BY not between", value1, value2, "lastUpdBy");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeIsNull() {
            addCriterion("LAST_UPD_TIME is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeIsNotNull() {
            addCriterion("LAST_UPD_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeEqualTo(String value) {
            addCriterion("LAST_UPD_TIME =", value, "lastUpdTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeNotEqualTo(String value) {
            addCriterion("LAST_UPD_TIME <>", value, "lastUpdTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeGreaterThan(String value) {
            addCriterion("LAST_UPD_TIME >", value, "lastUpdTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeGreaterThanOrEqualTo(String value) {
            addCriterion("LAST_UPD_TIME >=", value, "lastUpdTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeLessThan(String value) {
            addCriterion("LAST_UPD_TIME <", value, "lastUpdTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeLessThanOrEqualTo(String value) {
            addCriterion("LAST_UPD_TIME <=", value, "lastUpdTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeLike(String value) {
            addCriterion("LAST_UPD_TIME like", value, "lastUpdTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeNotLike(String value) {
            addCriterion("LAST_UPD_TIME not like", value, "lastUpdTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeIn(List<String> values) {
            addCriterion("LAST_UPD_TIME in", values, "lastUpdTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeNotIn(List<String> values) {
            addCriterion("LAST_UPD_TIME not in", values, "lastUpdTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeBetween(String value1, String value2) {
            addCriterion("LAST_UPD_TIME between", value1, value2, "lastUpdTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdTimeNotBetween(String value1, String value2) {
            addCriterion("LAST_UPD_TIME not between", value1, value2, "lastUpdTime");
            return (Criteria) this;
        }

        public Criteria andModificationNumIsNull() {
            addCriterion("MODIFICATION_NUM is null");
            return (Criteria) this;
        }

        public Criteria andModificationNumIsNotNull() {
            addCriterion("MODIFICATION_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andModificationNumEqualTo(Integer value) {
            addCriterion("MODIFICATION_NUM =", value, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumNotEqualTo(Integer value) {
            addCriterion("MODIFICATION_NUM <>", value, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumGreaterThan(Integer value) {
            addCriterion("MODIFICATION_NUM >", value, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("MODIFICATION_NUM >=", value, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumLessThan(Integer value) {
            addCriterion("MODIFICATION_NUM <", value, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumLessThanOrEqualTo(Integer value) {
            addCriterion("MODIFICATION_NUM <=", value, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumIn(List<Integer> values) {
            addCriterion("MODIFICATION_NUM in", values, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumNotIn(List<Integer> values) {
            addCriterion("MODIFICATION_NUM not in", values, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumBetween(Integer value1, Integer value2) {
            addCriterion("MODIFICATION_NUM between", value1, value2, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andModificationNumNotBetween(Integer value1, Integer value2) {
            addCriterion("MODIFICATION_NUM not between", value1, value2, "modificationNum");
            return (Criteria) this;
        }

        public Criteria andParentInfoPkidIsNull() {
            addCriterion("PARENT_INFO_PKID is null");
            return (Criteria) this;
        }

        public Criteria andParentInfoPkidIsNotNull() {
            addCriterion("PARENT_INFO_PKID is not null");
            return (Criteria) this;
        }

        public Criteria andParentInfoPkidEqualTo(String value) {
            addCriterion("PARENT_INFO_PKID =", value, "parentInfoPkid");
            return (Criteria) this;
        }

        public Criteria andParentInfoPkidNotEqualTo(String value) {
            addCriterion("PARENT_INFO_PKID <>", value, "parentInfoPkid");
            return (Criteria) this;
        }

        public Criteria andParentInfoPkidGreaterThan(String value) {
            addCriterion("PARENT_INFO_PKID >", value, "parentInfoPkid");
            return (Criteria) this;
        }

        public Criteria andParentInfoPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PARENT_INFO_PKID >=", value, "parentInfoPkid");
            return (Criteria) this;
        }

        public Criteria andParentInfoPkidLessThan(String value) {
            addCriterion("PARENT_INFO_PKID <", value, "parentInfoPkid");
            return (Criteria) this;
        }

        public Criteria andParentInfoPkidLessThanOrEqualTo(String value) {
            addCriterion("PARENT_INFO_PKID <=", value, "parentInfoPkid");
            return (Criteria) this;
        }

        public Criteria andParentInfoPkidLike(String value) {
            addCriterion("PARENT_INFO_PKID like", value, "parentInfoPkid");
            return (Criteria) this;
        }

        public Criteria andParentInfoPkidNotLike(String value) {
            addCriterion("PARENT_INFO_PKID not like", value, "parentInfoPkid");
            return (Criteria) this;
        }

        public Criteria andParentInfoPkidIn(List<String> values) {
            addCriterion("PARENT_INFO_PKID in", values, "parentInfoPkid");
            return (Criteria) this;
        }

        public Criteria andParentInfoPkidNotIn(List<String> values) {
            addCriterion("PARENT_INFO_PKID not in", values, "parentInfoPkid");
            return (Criteria) this;
        }

        public Criteria andParentInfoPkidBetween(String value1, String value2) {
            addCriterion("PARENT_INFO_PKID between", value1, value2, "parentInfoPkid");
            return (Criteria) this;
        }

        public Criteria andParentInfoPkidNotBetween(String value1, String value2) {
            addCriterion("PARENT_INFO_PKID not between", value1, value2, "parentInfoPkid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table EPSS.OPER_RES_TASK
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 03 10:18:28 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table EPSS.OPER_RES_TASK
     *
     * @mbggenerated Wed Sep 03 10:18:28 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}