package epss.repository.model;

import java.math.BigDecimal;

public class ProgStlItemSubM {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.PROG_STL_ITEM_SUB_M.PKID
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.PROG_STL_ITEM_SUB_M.PERIOD_NO
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    private String periodNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.PROG_STL_ITEM_SUB_M.SUBCTT_PKID
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    private String subcttPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.PROG_STL_ITEM_SUB_M.SUBCTT_ITEM_PKID
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    private String subcttItemPkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.PROG_STL_ITEM_SUB_M.BEGIN_TO_CURRENT_PERIOD_M_QTY
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    private BigDecimal beginToCurrentPeriodMQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.PROG_STL_ITEM_SUB_M.CURRENT_PERIOD_M_QTY
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    private BigDecimal currentPeriodMQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.PROG_STL_ITEM_SUB_M.M_PURCHASE_UNIT_PRICE
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    private BigDecimal mPurchaseUnitPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.PROG_STL_ITEM_SUB_M.ARCHIVED_FLAG
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    private String archivedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.PROG_STL_ITEM_SUB_M.CREATED_BY
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.PROG_STL_ITEM_SUB_M.CREATED_TIME
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    private String createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.PROG_STL_ITEM_SUB_M.LAST_UPD_BY
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    private String lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.PROG_STL_ITEM_SUB_M.LAST_UPD_TIME
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    private String lastUpdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.PROG_STL_ITEM_SUB_M.REC_VERSION
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    private Integer recVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EPSS.PROG_STL_ITEM_SUB_M.REMARK
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.PROG_STL_ITEM_SUB_M.PKID
     *
     * @return the value of EPSS.PROG_STL_ITEM_SUB_M.PKID
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.PROG_STL_ITEM_SUB_M.PKID
     *
     * @param pkid the value for EPSS.PROG_STL_ITEM_SUB_M.PKID
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.PROG_STL_ITEM_SUB_M.PERIOD_NO
     *
     * @return the value of EPSS.PROG_STL_ITEM_SUB_M.PERIOD_NO
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public String getPeriodNo() {
        return periodNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.PROG_STL_ITEM_SUB_M.PERIOD_NO
     *
     * @param periodNo the value for EPSS.PROG_STL_ITEM_SUB_M.PERIOD_NO
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public void setPeriodNo(String periodNo) {
        this.periodNo = periodNo == null ? null : periodNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.PROG_STL_ITEM_SUB_M.SUBCTT_PKID
     *
     * @return the value of EPSS.PROG_STL_ITEM_SUB_M.SUBCTT_PKID
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public String getSubcttPkid() {
        return subcttPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.PROG_STL_ITEM_SUB_M.SUBCTT_PKID
     *
     * @param subcttPkid the value for EPSS.PROG_STL_ITEM_SUB_M.SUBCTT_PKID
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public void setSubcttPkid(String subcttPkid) {
        this.subcttPkid = subcttPkid == null ? null : subcttPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.PROG_STL_ITEM_SUB_M.SUBCTT_ITEM_PKID
     *
     * @return the value of EPSS.PROG_STL_ITEM_SUB_M.SUBCTT_ITEM_PKID
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public String getSubcttItemPkid() {
        return subcttItemPkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.PROG_STL_ITEM_SUB_M.SUBCTT_ITEM_PKID
     *
     * @param subcttItemPkid the value for EPSS.PROG_STL_ITEM_SUB_M.SUBCTT_ITEM_PKID
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public void setSubcttItemPkid(String subcttItemPkid) {
        this.subcttItemPkid = subcttItemPkid == null ? null : subcttItemPkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.PROG_STL_ITEM_SUB_M.BEGIN_TO_CURRENT_PERIOD_M_QTY
     *
     * @return the value of EPSS.PROG_STL_ITEM_SUB_M.BEGIN_TO_CURRENT_PERIOD_M_QTY
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public BigDecimal getBeginToCurrentPeriodMQty() {
        return beginToCurrentPeriodMQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.PROG_STL_ITEM_SUB_M.BEGIN_TO_CURRENT_PERIOD_M_QTY
     *
     * @param beginToCurrentPeriodMQty the value for EPSS.PROG_STL_ITEM_SUB_M.BEGIN_TO_CURRENT_PERIOD_M_QTY
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public void setBeginToCurrentPeriodMQty(BigDecimal beginToCurrentPeriodMQty) {
        this.beginToCurrentPeriodMQty = beginToCurrentPeriodMQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.PROG_STL_ITEM_SUB_M.CURRENT_PERIOD_M_QTY
     *
     * @return the value of EPSS.PROG_STL_ITEM_SUB_M.CURRENT_PERIOD_M_QTY
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public BigDecimal getCurrentPeriodMQty() {
        return currentPeriodMQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.PROG_STL_ITEM_SUB_M.CURRENT_PERIOD_M_QTY
     *
     * @param currentPeriodMQty the value for EPSS.PROG_STL_ITEM_SUB_M.CURRENT_PERIOD_M_QTY
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public void setCurrentPeriodMQty(BigDecimal currentPeriodMQty) {
        this.currentPeriodMQty = currentPeriodMQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.PROG_STL_ITEM_SUB_M.M_PURCHASE_UNIT_PRICE
     *
     * @return the value of EPSS.PROG_STL_ITEM_SUB_M.M_PURCHASE_UNIT_PRICE
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public BigDecimal getmPurchaseUnitPrice() {
        return mPurchaseUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.PROG_STL_ITEM_SUB_M.M_PURCHASE_UNIT_PRICE
     *
     * @param mPurchaseUnitPrice the value for EPSS.PROG_STL_ITEM_SUB_M.M_PURCHASE_UNIT_PRICE
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public void setmPurchaseUnitPrice(BigDecimal mPurchaseUnitPrice) {
        this.mPurchaseUnitPrice = mPurchaseUnitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.PROG_STL_ITEM_SUB_M.ARCHIVED_FLAG
     *
     * @return the value of EPSS.PROG_STL_ITEM_SUB_M.ARCHIVED_FLAG
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public String getArchivedFlag() {
        return archivedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.PROG_STL_ITEM_SUB_M.ARCHIVED_FLAG
     *
     * @param archivedFlag the value for EPSS.PROG_STL_ITEM_SUB_M.ARCHIVED_FLAG
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public void setArchivedFlag(String archivedFlag) {
        this.archivedFlag = archivedFlag == null ? null : archivedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.PROG_STL_ITEM_SUB_M.CREATED_BY
     *
     * @return the value of EPSS.PROG_STL_ITEM_SUB_M.CREATED_BY
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.PROG_STL_ITEM_SUB_M.CREATED_BY
     *
     * @param createdBy the value for EPSS.PROG_STL_ITEM_SUB_M.CREATED_BY
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.PROG_STL_ITEM_SUB_M.CREATED_TIME
     *
     * @return the value of EPSS.PROG_STL_ITEM_SUB_M.CREATED_TIME
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.PROG_STL_ITEM_SUB_M.CREATED_TIME
     *
     * @param createdTime the value for EPSS.PROG_STL_ITEM_SUB_M.CREATED_TIME
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime == null ? null : createdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.PROG_STL_ITEM_SUB_M.LAST_UPD_BY
     *
     * @return the value of EPSS.PROG_STL_ITEM_SUB_M.LAST_UPD_BY
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.PROG_STL_ITEM_SUB_M.LAST_UPD_BY
     *
     * @param lastUpdBy the value for EPSS.PROG_STL_ITEM_SUB_M.LAST_UPD_BY
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.PROG_STL_ITEM_SUB_M.LAST_UPD_TIME
     *
     * @return the value of EPSS.PROG_STL_ITEM_SUB_M.LAST_UPD_TIME
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public String getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.PROG_STL_ITEM_SUB_M.LAST_UPD_TIME
     *
     * @param lastUpdTime the value for EPSS.PROG_STL_ITEM_SUB_M.LAST_UPD_TIME
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public void setLastUpdTime(String lastUpdTime) {
        this.lastUpdTime = lastUpdTime == null ? null : lastUpdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.PROG_STL_ITEM_SUB_M.REC_VERSION
     *
     * @return the value of EPSS.PROG_STL_ITEM_SUB_M.REC_VERSION
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public Integer getRecVersion() {
        return recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.PROG_STL_ITEM_SUB_M.REC_VERSION
     *
     * @param recVersion the value for EPSS.PROG_STL_ITEM_SUB_M.REC_VERSION
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public void setRecVersion(Integer recVersion) {
        this.recVersion = recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EPSS.PROG_STL_ITEM_SUB_M.REMARK
     *
     * @return the value of EPSS.PROG_STL_ITEM_SUB_M.REMARK
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EPSS.PROG_STL_ITEM_SUB_M.REMARK
     *
     * @param remark the value for EPSS.PROG_STL_ITEM_SUB_M.REMARK
     *
     * @mbggenerated Wed Dec 10 15:26:33 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}